const fs = require('fs');
let c = fs.readFileSync('LearnSpanishApp.tsx', 'utf-8');

c = c.replace(/App/g, 'LearnSpanishApp');
c = c.replace(/import \{ LearnSpanishApp \} from '\.\/LearnSpanishApp';\n/g, '');
c = c.replace(/import \{ Layout \} from '\.\/components\/Layout';/g, "import { Layout } from './components/Layout';");
c = c.replace(/import \{ WordSpan \} from '\.\/components\/WordSpan';/g, "import { LearnSpanishWordSpan } from './components/LearnSpanishWordSpan';");
c = c.replace(/import \{ STORIES \} from '\.\/constants';/g, "import { LEARN_SPANISH_STORIES } from './learnSpanishConstants';");
c = c.replace(/import \{ LearnSpanishAppState, Story, Question, Word \} from '\.\/types';/g, "import { LearnSpanishAppState, LearnSpanishStory, LearnSpanishQuestion, LearnSpanishWord } from './learnSpanishTypes';");
c = c.replace(/prepareMandarinTTS/g, 'prepareLearnSpanishTTS');
c = c.replace(/prepareConversationTTS/g, 'prepareLearnSpanishConversationTTS');
c = c.replace(/mandarin_echo_vocab/g, 'learn_spanish_echo_vocab');
c = c.replace(/Word\[\]/g, 'LearnSpanishWord[]');
c = c.replace(/Story \| null/g, 'LearnSpanishStory | null');
c = c.replace(/Story,/g, 'LearnSpanishStory,');
c = c.replace(/Question /g, 'LearnSpanishQuestion ');
c = c.replace(/WordSpan/g, 'LearnSpanishWordSpan');
c = c.replace(/STORIES/g, 'LEARN_SPANISH_STORIES');
c = c.replace(/\.mandarin/g, '.spanish');
c = c.replace(/questionMandarin/g, 'questionSpanish');
c = c.replace(/'pinyin' \| 'hanzi' \| 'english'/g, "'english' | 'spanish'");
c = c.replace(/setVocabSort\('pinyin'\)/g, "setVocabSort('english')");
c = c.replace(/vocabSort === 'pinyin'/g, "vocabSort === 'english'");
c = c.replace(/vocabSort === 'hanzi'/g, "vocabSort === 'spanish'");
c = c.replace(/>Pinyin</g, '>English<');
c = c.replace(/>Hanzi</g, '>Spanish<');
c = c.replace(/\.pinyin/g, '.english');
c = c.replace(/\.hanzi/g, '.spanish');
c = c.replace(/from-violet-600/g, 'from-amber-600');
c = c.replace(/to-indigo-600/g, 'to-orange-600');
c = c.replace(/border-violet-400/g, 'border-amber-400');
c = c.replace(/text-violet-400/g, 'text-amber-400');
c = c.replace(/bg-violet-500/g, 'bg-amber-500');
c = c.replace(/text-violet-300/g, 'text-amber-300');
c = c.replace(/headerTitle="Mandarin Echo"/g, 'headerTitle="Spanish"');
c = c.replace(/<span className="text-white block">\{s\.spanish\}<\/span>/g, '<span className="text-white block">{s.english}</span>');
c = c.replace(/<span className="text-slate-400 text-lg block mt-2">\{s\.english\}<\/span>/g, '<span className="text-slate-400 text-lg block mt-2">{s.spanish}</span>');

fs.writeFileSync('LearnSpanishApp.tsx', c);
console.log('Done replacement');
